# This workflow will do a clean install of node dependencies, cache/restore them, and build then lint the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js v16.1.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.1.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test typescript build
        run: yarn tsc --noEmit

      - name: Run ESLint
        run: yarn eslint ./server
